# Generated by Django 4.2.3 on 2023-12-08 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_client_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
