# Generated by Django 4.2.3 on 2023-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_stat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
