# Generated by Django 4.2.3 on 2023-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_stat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='value',
        ),
        migrations.AddField(
            model_name='game',
            name='game_ending_type',
            field=models.CharField(choices=[('third_set_normal', 'Third Set Normal'), ('super_tie_break', 'Super Tie Break')], default='third_set_normal', max_length=50),
        ),
    ]
