# Generated by Django 4.2.3 on 2023-12-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_stat_value_game_game_ending_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='parent_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_stat', to='backend.stat'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('UTR', 'UTR'), ('normal', 'Normal')], max_length=50),
        ),
    ]
