# Generated by Django 4.2.3 on 2023-12-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_stat_parent_stat_alter_game_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='parent_stat',
        ),
    ]
