# Generated by Django 4.2.3 on 2023-12-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_stat_parent_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typestat',
            name='parent_stat',
        ),
    ]
